Feature/routing 5
18-Santa-Barbara/fishing-game pull request #5
Opened 2022-10-24 16:02 UTC by petagys

### Sprint 5

2022-10-24 18:49 UTC, ivan-infro requested changes

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/vite.config.ts.timestamp-1666130427713.mjs
> +// vite.config.ts
какой-то временный файл, в репозиторий его коммитить не нужно было. Всегда просматривайте повторно все файлы, которые собираетесь закоммитить. Все что попало в git, остается в нем навсегда. Можно запушить удаление файла, но он все-равно будет в истории (особенно это важно, если в репу попал файл с паролями, например).

P.S. Можно "переписать историю" и тогда удаление будет почти настоящим. Но это не удалит файл с устройств, где был git pull сделали раньше

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Login.tsx
> +    // display: 'flex',
Не коммитьте закомментированный и неиспользуемый код, это ухудшает читаемость кода

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Login.tsx
> +  function submit(e) {
Подсмотреть, какого типа переменная приходит в обработчик, можно перейдя к самому событию
<img width="640" alt="Screenshot 2022-10-24 at 20 12 30" src="https://user-images.githubusercontent.com/5419627/197596574-1dbd33be-c523-4405-81ad-117ff190b32e.png">
Как обсуждали на созвоне, тут нам достаточно обработчика отправки формы, поэтому `e: FormEvent`

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Login.tsx
> +          console.log(res);
Избегайте лишнего логирования, либо используйте console.debug

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/leaderboard.tsx
> +import React from "react";
Файл назван с маленькой буквы, а все остальные с большой. Всегда используйте единый стиль.

Если у вас регистронезависимая файловая система (по умолчанию в macOS), чтобы поменять только регистр буквы, надо закоммитить удаление файла и затем, отдельным коммитом, добавить его обратно уже с правильным названием

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/leaderboard.tsx
> +    apiRequestPost(`${API}/leaderboard/SantaBarbara`, data)
Функция render не должна иметь побочных эффектов! Используйте useEffect хук, иначе запрос будет вызываться на каждый render:

<img width="918" alt="Screenshot 2022-10-24 at 20 23 28" src="https://user-images.githubusercontent.com/5419627/197598230-049a3e6f-f1e2-46dd-9831-c1d223f417ba.png">

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/components/leaderboard/styles/board.css
> +    font-size: 2rem !important;
Никогда не используйте important!
Стили с таким модификатором сложно переопределить, это снижает переиспользуемость кода

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/components/leaderboard/profile.tsx
> +const Profiles = ({ Players }: Player[]) => {
Тут неправильно задан тип
`{ Players }` - это деструктуризация объекта
`: Player[]` - означает что слева от двоеточия находится массив 
правильно так: `{ Players }: { Players: Player[] }`

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/components/leaderboard/profile.tsx
> +                    <Card className="profile__card">
У каждого элемента в рендере массива должен быть атрибут key

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Forum.tsx
> +import {
В дальнейшем необходимо поделить на компоненты поменьше

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Forum.tsx
> +            id="comment"
Здесь не хватает `value={comment}`, ведь обработчик сверху его очищает (а поле при этом остается с текстом)

2022-10-24 18:49 UTC, ivan-infro commented on packages/client/src/pages/Forum.tsx
> +    setPostList(rows);
Не вызовет повторный render, потому что ссылка на массив осталась та же

2022-10-24 19:45 UTC, petagys commented on packages/client/src/pages/Login.tsx
> +  function submit(e) {
Сделал, но у preventDefault все равно ошибка:
![image](https://user-images.githubusercontent.com/44364556/197612429-af382491-f378-4d83-a68f-b8994e86a848.png)

2022-10-29 23:24 UTC, ivan-infro requested changes

2022-10-29 23:24 UTC, ivan-infro commented on packages/client/src/App.tsx
> +import { Leaderboard } from './pages/Leaderboard';
Сейчас имя файла и импорт не совпадают (в импорте L, в репозитории файл с маленькой буквы закоммичен), поэтому в системе с регистрозависимой файловой системой проект не собирается)

2022-12-06 18:36 UTC, merged